/**
 * Generates a unique color for a given email address.
 * The color is generated by hashing the email and mapping it to a hue value.
 *
 * @param email - The email address to generate the color for.
 * @returns A hex color string (e.g., "#a1b2c3").
 */
export function getColorFromEmail(email: string): string {
  let hash = 0;
  for (let i = 0; i < email.length; i++) {
    hash = email.charCodeAt(i) + ((hash << 5) - hash);
    hash = hash & hash; // Convert to 32bit integer
  }

  const hue = Math.abs(hash) % 360;

  const saturation = 50;
  const lightness = 50;

  // Convert HSL to hex color
  return hslToHex(hue, saturation, lightness);
}

/**
 * Converts HSL color values to a hex color string.
 *
 * @param h - Hue component (0 - 360)
 * @param s - Saturation component (0 - 100)
 * @param l - Lightness component (0 - 100)
 * @returns A hex color string (e.g., "#a1b2c3").
 */
function hslToHex(h: number, s: number, l: number): string {
  s /= 100;
  l /= 100;

  const c = (1 - Math.abs(2 * l - 1)) * s;
  const x = c * (1 - Math.abs(((h / 60) % 2) - 1));
  const m = l - c / 2;
  let r = 0,
    g = 0,
    b = 0;

  if (0 <= h && h < 60) {
    r = c;
    g = x;
    b = 0;
  } else if (60 <= h && h < 120) {
    r = x;
    g = c;
    b = 0;
  } else if (120 <= h && h < 180) {
    r = 0;
    g = c;
    b = x;
  } else if (180 <= h && h < 240) {
    r = 0;
    g = x;
    b = c;
  } else if (240 <= h && h < 300) {
    r = x;
    g = 0;
    b = c;
  } else if (300 <= h && h < 360) {
    r = c;
    g = 0;
    b = x;
  }

  const toHex = (val: number) => {
    const hex = Math.round((val + m) * 255).toString(16);
    return hex.length === 1 ? "0" + hex : hex;
  };

  return `#${toHex(r)}${toHex(g)}${toHex(b)}`;
}
