
export enum AuthMessageType {
    SUCCESS = "SUCCESS",
    FAILURE = "FAILURE",
}
export enum AuthActionType {
    LOGIN_SUCCESS = "LOGIN_SUCCESS",
    LOGIN_FAILURE = "LOGIN_FAILURE",
    REGISTER_SUCCESS = "REGISTER_SUCCESS",
    REGISTER_FAILURE = "REGISTER_FAILURE",
    LOGOUT_SUCCESS = "LOGOUT_SUCCESS",
    LOGOUT_FAILURE = "LOGOUT_FAILURE",
    AUTH_ERROR = "AUTH_ERROR",
    AUTH_CLEAR = "AUTH_CLEAR",
}