export enum MenuAction {
    SelectionMode = "selection-mode",
    DrawingMode = "drawing-mode",
    EraserMode = "eraser-mode",
    ChangeColor = "change-color",
    ChangeSize = "change-size",
    AddLine = "add-line",
    AddRectangle = "add-rectangle",
    AddCircle = "add-circle",
    AddText = "add-text",
    ClearCanvas = "clear-canvas",
    AddImageUrl = "add-image-url",
    AddImageDisk = "add-image-disk",
    ExportPdf = "export-pdf",
    Undo = "undo",
    Redo = "redo",
    LoadCanvas = "load-canvas",
    SaveCanvas = "save-canvas",
    SaveImages = "save-images",
    LoadImagesJson = "load-images-json",
    GroupSelected = "group-selected",
    RemoveSelected = "remove-selected"
}
