import type { Metadata } from "next";
import { Inter, Anek_Devanagari,Aldrich } from "next/font/google";
import "./globals.css";

const anekDev = Anek_Devanagari({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Obelisk",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${anekDev.className} bg-palette1-darkest-blue-template1`}>{children}</body>
    </html>
  );
}
