services:

  client:
    build:
      context: ./client
      args:
        - SERVER_HOST=server
        - SERVER_PORT
        - GOOGLE_CLIENT_ID
        - GOOGLE_CLIENT_SECRET
        - GOOGLE_CALLBACK_URL
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    container_name: obelisk_client_container
    environment:
      - CLIENT_HOST
      - CLIENT_PORT


  server:
    build: ./server
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    container_name: obelisk_server_container
    depends_on:
      - mongo
    environment:
      - SERVER_HOST
      - SERVER_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST=mongo # must be set to mongo
      - DB_PORT
      - JWT_SECRET
      - JWT_EXPIRES_IN
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_CALLBACK_URL

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # must be set to 27017
    container_name: obelisk_mongodb_container
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
