version: '3'

services:

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    container_name: obelisk_frontend_container

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: obelisk_backend_container