services:

  frontend:
    build:
      context: ./frontend
      args:
        - BACKEND_HOST=backend
        - BACKEND_PORT
        - GOOGLE_CLIENT_ID
        - GOOGLE_CLIENT_SECRET
        - GOOGLE_CALLBACK_URL
    ports:
      - "${FRONTEND_PORT}:${FRONTEND_PORT}"
    container_name: obelisk_frontend_container
    environment:
      - FRONTEND_HOST
      - FRONTEND_PORT
      - BACKEND_HOST=backend
      - BACKEND_PORT

  backend:
    build: ./backend
    ports:
      - "${BACKEND_PORT}:${BACKEND_PORT}"
    container_name: obelisk_backend_container
    depends_on:
      - mongo
    environment:
      - BACKEND_HOST
      - BACKEND_PORT
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST=mongo # must be set to mongo
      - DB_PORT
      - JWT_SECRET
      - JWT_EXPIRES_IN
      - GOOGLE_EMAIL
      - GOOGLE_PASSWORD
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - GOOGLE_CALLBACK_URL
      - SESSION_SECRET
      - COOKIE_SESSION_MAX_AGE
      - THROTTLE_TTL
      - THROTTLE_LIMIT

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017" # must be set to 27017
    container_name: obelisk_mongodb_container
    environment:
      - MONGO_INITDB_DATABASE=${DB_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
