export enum MenuActions {
  CHANGE_COLOR = "change-color",
  CHANGE_SIZE = "change-size",
  ADD_LINE = "add-line",
  ADD_RECTANGLE = "add-rectangle",
  ADD_CIRCLE = "add-circle",
  ADD_TEXT = "add-text",
  CLEAR_CANVAS = "clear-canvas",
  ADD_IMAGE_URL = "add-image-url",
  ADD_IMAGE_DISK = "add-image-disk",
  EXPORT_PDF = "export-pdf",
  UNDO = "undo",
  REDO = "redo",
  LOAD_CANVAS = "load-canvas",
  SAVE_CANVAS = "save-canvas",
  SAVE_IMAGES = "save-images",
  LOAD_IMAGES_JSON = "load-images-json",
  GROUP_SELECTED = "group-selected",
  REMOVE_SELECTED = "remove-selected",
}
