name: backend

on:
  push:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: backend/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-deps
          restore-keys: |
            ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: cd backend && npm install

      - name: Build
        run: cd backend && npm run build

      - name: Lint
        run: cd backend && npm run lint

      - name: Unit tests
        run: cd backend && npm run test

      - name: e2e tests
        run: cd backend && npm run test:e2e

      - name: Code coverage
        run: cd backend && npm run test:cov
