name: 'conventional-commit-checker'

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  validate-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Commit Message Checker
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^[a-z]+(\([a-z0-9\-]+\))?: .+$'
          flags: 'gm'
