name: 'conventional-commit-checker'

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  validate-commit-message:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Commit Message Checker
        uses: gsactions/commit-message-checker@v2
        with:
          pattern: '^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-zA-Z0-9\-]+\))?\[[a-zA-Z0-9\-]+\] [A-Z].+$'
          flags: 'gm'
          error: 'Commit message does not follow conventional commits rules. Pattern: `^(feat|fix|docs|style|refactor|perf|test|build|ci|chore|revert)(\([a-zA-Z0-9\-]+\))?\[[a-zA-Z0-9\-]+\] [A-Z].+$`'
