name: server

on:
  push:

jobs:
  server-pipeline:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Cache dependencies
        id: cache
        uses: actions/cache@v3
        with:
          path: server/node_modules
          key: ${{ runner.os }}-node-${{ matrix.node-version }}-deps
          restore-keys: ${{ runner.os }}-node-${{ matrix.node-version }}-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install
        working-directory: server

      - name: Verify dependencies
        run: npm install -g depcheck && depcheck
        working-directory: server

      - name: Build
        run: npm run build
        working-directory: server

      - name: Lint
        run: npm run lint
        working-directory: server

      - name: Unit tests
        run: npm run test
        working-directory: server

#      - name: e2e tests
#        run: npm run test:e2e
#        working-directory: backend

#      - name: Code coverage
#        run: npm run test:cov
#        working-directory: backend
